name: Deploying to Cloud Run 0.1

on:
    push:
        branches:
            - "firebase"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with Google Cloud
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GG_CREDENTIAL }}"

            - name: Configure docker
              run: gcloud auth configure-docker us-east1-docker.pkg.dev

            - name: Copy Firebase JSON
              working-directory: .
              env:
                FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
              run: |
                mkdir cred
                echo $FIREBASE_JSON >> ./cred/firebase_key.json

            - name: Build and push Backend docker image
              uses: docker/build-push-action@v2
              with: 
                  context: .
                  file: ./Dockerfile
                  build-args: |
                      ENV_SERVICE_ACCOUNT_KEY: ${{ secrets.ENV_SERVICE_ACCOUNT_KEY }}
                      ENV_COOKIES: ${{ secrets.ENV_COOKIES }}
                  push: true
                  tags: us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/crawler/runner:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Authenticate with Google Cloud
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GG_CREDENTIAL }}"

            - name: Deploy Backend to Cloud Run
              uses: "google-github-actions/deploy-cloudrun@v1"
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  service: "${{ secrets.PROJECT_SERVICE }}"
                  region: "us-east1"
                  image: "us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/crawler/runner:latest"
